root: true
env:
  browser: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'prettier'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 15
  sourceType: module
ignorePatterns:
  - 'test/**/*.spec.ts'
